name: CMake
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:

	
  STACKUSEPOISON:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSECANARY:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_CANARY "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSECANARY:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_CANARY "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSECANARY:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSECANARY-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSECANARY-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_CANARY  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSECANARY:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSECANARY-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSECANARY-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_CANARY  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSECANARY-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSECANARY-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSECANARY-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSECANARY-STACKUSESTRUCTHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSECANARY-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSEPTRPOISON-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_PTR_POISON  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPOISON-STACKUSECANARY-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_POISON  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
	
  STACKUSEPTRPOISON-STACKUSECANARY-STACKUSESTRUCTHASH-STACKUSEDATAHASH:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Sanitizer -D CMAKE_CXX_FLAGS=" ${CMAKE_CXX_FLAGS}  -D STACK_USE_PTR_POISON  -D STACK_USE_CANARY  -D STACK_USE_STRUCT_HASH  -D STACK_USE_DATA_HASH "

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Sanitizer

    - name: Test
      working-directory: ${{github.workspace}}/build/
      run: ./stack-test
